### ISSUE TITLE
/sgon after every single server restart

### ISSUE THREAD

**Issue by At0mkern** [DavidS-Repo/SkyGridx#1]
hi,

i need to do /sgon after every single server restart. if i dont, nothing will be generated in new chunks. this is kinda annoying when using servers that restart every once in a while. would be nice if the generation enables itself after the server starts and the plugin gets loaded

**Comment by DavidS-Repo** [comment]
**Update: Removed /sgon**

Hi At0mkern,

I've eliminated the need for "/sgon" after each server restart. Now, SkyGrid generation automatically activates when the server starts or is reloaded. No more manual steps required!

The updated JAR is on the main branch, or you can get it directly [here](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid.jar). If you run into any hiccups or have suggestions, please let me know.

Best,
David

**Comment by At0mkern** [comment]
Thank you for your rapid response & fix - ill test it right away :)
