### ISSUE TITLE
Configurable tpr

### ISSUE THREAD

**Issue by CorentinStauder** [DavidS-Repo/SkyGridx#5]
Hello,

Nice plugin, I will fully implement it on my server !

Will it be possible to have a config file that allow or disallow the tpr commands for each dimension ? and a way to set the maximum distance of those tpr ?
Or maybe to have permissions associated with each of tpr allowing us to define who have access to that commands.

For example in my case I want my players to be able to /tpr only in the overworld within a maximum distance of 10 000 blocks.

thanks !

**Comment by DavidS-Repo** [comment]
Hello @CorentinStauder,

Thank you for the feature request and for your kind words about the plugin!

I have actually been working on a new settings file that will include configuration options for further fine-tuning the grid generator and more. This update already includes settings for the /tpr command, such as the cooldown timer, teleportation range, and other configurable options. I plan to release this update on Wednesday.

Regarding the permissions for /tpr, I can add this feature before the release. Currently, /tpr is a single command with optional inputs for the Nether or End. I can modify this to create separate commands for each dimension, allowing for individual permissions. This way, you can manage permissions using permission plugins to control who can use each command.

Thank you for your suggestion.

Best,
David

**Comment by DavidS-Repo** [comment]
Implemented settings file to add /tpr range and cooldown timer, it can be found in the plugin folder after boot.
Permission settings, will come later (5-22-2024)

The updated version of the jar is available in the [main page](https://github.com/DavidS-Repo/SkyGridx).
[SkyGrid.jar](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid.jar) or here directly.

**Comment by CorentinStauder** [comment]
That's perfect, range and cooldown are working great !

**Comment by DavidS-Repo** [comment]
Hello @CorentinStauder, 

Here are the updated permission and commands.
Let me know if you run into any problems.

The updated version of the jar is available in the [main page](https://github.com/DavidS-Repo/SkyGridx).
[SkyGrid.jar](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid.jar) or here directly.

# Commands:

- **/tpr [world]** (random teleport in a specified environment; Overworld, Nether, or End)
- **/tpro** (random teleport in the Overworld)
- **/tprn** (random teleport in the Nether)
- **/tpre** (random teleport in the End)
- **/fogon** (turns fog on)
- **/fogoff** (turns fog off)
- **/gclogson** (turns on growth control logs)
- **/gclogsoff** (turns off growth control logs)
- **/pregen** (Pregenerates the overworld, nether and end)
- **/pregenoff** (Turns of pregeneration process)
- **/patch** (Patch files to update materials and entities to newest version, if you update the plugin from an old version)

## Permissions:

- `sg.tpr`: Allows teleportation to overworld, nether, and end using the `/tpr [world]` command
- `sg.tpr.overworld`: Grants permission to use the `/tpro` command for teleportation in the overworld
- `sg.tpr.nether`: Grants permission to use the `/tprn` command for teleportation in the Nether
- `sg.tpr.end`: Enables usage of the `/tpre` command for teleportation in the End
- `sg.tpr.*`: Provides access to all teleportation commands
- `sg.fogon`: Allows enabling fog using the `/fogon` command
- `sg.fogoff`: Allows disabling fog with the `/fogoff` command
- `sg.gclogson`: Grants permission to enable GrowthControl logging using `/gclogson`
- `sg.gclogsoff`: Grants permission to disable GrowthControl logging using `/gclogsoff`
- `sg.pregen`: Grants permission to use the pre-generation command with customizable parameters
- `sg.pregenoff`: Grants permission to disable pre-generation using the `/pregenoff` command
- `sg.patch`: Allows patching files to update materials and entities to another version
- `sg.regen`: Grants permission to regenerate all loaded chunks using the `/regen` command
- `sg.*`: Provides access to all SkyGrid commands

**Comment by CorentinStauder** [comment]
No problem, works as expected ! Thanks
