### ISSUE TITLE
OreGenerator does not work while generating stone

### ISSUE THREAD

**Issue by KotShahter** [DavidS-Repo/SkyGridx#7]
As far as I am concerned, currently OreGeneratorPlugin plugin does not work correctly. The issue occurs only when a player tries to generate stone. For some reason the stone generation can't be changed via the config and the blocks from the config just do not appear (even with buffed numbers). Interestingly, ore cobblestone generator works flawlessly and all blocks are changed into cobbled deepslate ores

Minecraft 1.21.3
Java jdk-22.0.1
Latest available spigot

**Comment by DavidS-Repo** [comment]
> As far as I am concerned, currently OreGeneratorPlugin plugin does not work correctly. The issue occurs only when a player tries to generate stone. For some reason the stone generation can't be changed via the config and the blocks from the config just do not appear (even with buffed numbers). Interestingly, ore cobblestone generator works flawlessly and all blocks are changed into cobbled deepslate ores
> 
> 
> 
> 
> 
> Minecraft 1.21.3
> 
> Java jdk-22.0.1
> 
> Latest avaliable bukkit

I’ll look into this tonight. In the meantime, could you let me know if you are running any other plugins? This will help me test for any possible conflicts. Thanks!

**Comment by KotShahter** [comment]
> > As far as I am concerned, currently OreGeneratorPlugin plugin does not work correctly. The issue occurs only when a player tries to generate stone. For some reason the stone generation can't be changed via the config and the blocks from the config just do not appear (even with buffed numbers). Interestingly, ore cobblestone generator works flawlessly and all blocks are changed into cobbled deepslate ores
> > Minecraft 1.21.3
> > Java jdk-22.0.1
> > Latest avaliable bukkit
> 
> I’ll look into this tonight. In the meantime, could you let me know if you are running any other plugins? This will help me test for any possible conflicts. Thanks!



> I’ll look into this tonight. In the meantime, could you let me know if you are running any other plugins? This will help me test for any possible conflicts. Thanks!

Hi! I'm glad to see your fast reply!

I use only your plugin on a barebone spigot server that I host on my own PC just for myself. Obviously, I use VoidBiome datapack, which is provided in the installation instructions, I believe, this is it!

**Comment by KotShahter** [comment]
It was spigot server not bukkit!

**Comment by DavidS-Repo** [comment]
Hi @KotShahter, thank you for reporting this issue! The problem was due to the plugin only handling block formations triggered by lava, ignoring those triggered by water. This has been fixed, and ore replacement now works for stone generated by both water and lava.

The main repository has been updated with the fix, and you can download the latest .jar file here: [SkyGrid.jar](https://github.com/DavidS-Repo/SkyGridx/blob/main/SkyGrid.jar). Let me know if you encounter any further issues.

Thanks again for bringing this to my attention! Let me know if there’s anything else.
