### ISSUE TITLE
How To Add To Singleplayer World

### ISSUE THREAD

**Issue by Hellofortnitenei** [DavidS-Repo/SkyGridx#8]
Too Confusing Too Install

**Comment by Hellofortnitenei** [comment]
nvm i think i figured it out but can you plz make it a datapack

**Comment by Hellofortnitenei** [comment]
i dont want to do this everytime

**Comment by DavidS-Repo** [comment]
Hi @Hellofortniten,

Thanks for your feedback! If there’s something specific about the installation instructions that you found confusing, please let me know. Whether it’s a particular step or the entire process, I’d love to hear your thoughts so I can make the documentation clearer and easier to follow for everyone.

As for turning the plugin into a datapack, I appreciate the suggestion, but that’s unfortunately outside my expertise at the moment. When I worked on a simple datapack for wiping chunks and generated structures, it took me about a week to figure out the basics. Transforming the plugin into a fully functional datapack would require creating a completely new generator that works with Minecraft’s datapack system.

Additionally, a datapack would likely lose many of the customization options the plugin offers—like grid adjustments, spawner configurations, biome-specific generation, and other settings—which would have to be hardcoded into the datapack format (as far as I understand).

For now, my focus is on improving the plugin and its installation process. If there’s anything else you’d like to suggest or share about your experience, feel free to let me know! Thanks again for trying it out.
